plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cory.signalhunter'
    compileSdk 35

    defaultConfig {
        applicationId 'com.cory.signalhunter'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.3.0'
        testInstrumentationRunner 'com.cory.signalhunter.AnalystInstrumentation'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}
